<a href="https://colab.research.google.com/github/Haricharan-Venkatesh/exploratory-data-analysis-lab-exercises/blob/main/Exp4_28.07.2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

data = np.arange(100, 115).reshape(5, 3)
dfx = pd.DataFrame(data, index=['car', 'bike', 'truck', 'bus', 'train'], columns=['city1', 'city2', 'city3'])
dfx

       city1  city2  city3
car      100    101    102
bike     103    104    105
truck    106    107    108
bus      109    110    111
train    112    113    114

In [2]:
dfx['city4'] = np.nan
dfx.loc['bicycle'] = np.arange(100, 104)
dfx.loc['airplane'] = np.nan
dfx['city5'] = np.nan
dfx.loc['car', 'city4'] = 150.0
dfx

          city1  city2  city3  city4  city5
car       100.0  101.0  102.0  150.0    NaN
bike      103.0  104.0  105.0    NaN    NaN
truck     106.0  107.0  108.0    NaN    NaN
bus       109.0  110.0  111.0    NaN    NaN
train     112.0  113.0  114.0    NaN    NaN
bicycle   100.0  101.0  102.0  103.0    NaN
airplane    NaN    NaN    NaN    NaN    NaN

In [4]:
dfx.isnull()

          city1  city2  city3  city4  city5
car       False  False  False  False   True
bike      False  False  False   True   True
truck     False  False  False   True   True
bus       False  False  False   True   True
train     False  False  False   True   True
bicycle   False  False  False  False   True
airplane   True   True   True   True   True

In [5]:
dfx.notnull()

          city1  city2  city3  city4  city5
car        True   True   True   True  False
bike       True   True   True  False  False
truck      True   True   True  False  False
bus        True   True   True  False  False
train      True   True   True  False  False
bicycle    True   True   True   True  False
airplane  False  False  False  False  False

In [6]:
dfx.isnull().sum()

city1    1
city2    1
city3    1
city4    5
city5    7
dtype: int64

In [7]:
dfx.isnull().sum().sum()

np.int64(15)

In [8]:
dfx.count()

city1    6
city2    6
city3    6
city4    2
city5    0
dtype: int64

In [9]:
dfx.city4[dfx.city4.notnull()]

car        150.0
bicycle    103.0
Name: city4, dtype: float64

In [10]:
dfx.city4.dropna()

car        150.0
bicycle    103.0
Name: city4, dtype: float64

In [11]:
dfx.dropna()

Empty DataFrame
Columns: [city1, city2, city3, city4, city5]
Index: []

In [12]:
dfx.dropna(how='all')

         city1  city2  city3  city4  city5
car      100.0  101.0  102.0  150.0    NaN
bike     103.0  104.0  105.0    NaN    NaN
truck    106.0  107.0  108.0    NaN    NaN
bus      109.0  110.0  111.0    NaN    NaN
train    112.0  113.0  114.0    NaN    NaN
bicycle  100.0  101.0  102.0  103.0    NaN

In [13]:
dfx.dropna(how='all', axis=1)

          city1  city2  city3  city4
car       100.0  101.0  102.0  150.0
bike      103.0  104.0  105.0    NaN
truck     106.0  107.0  108.0    NaN
bus       109.0  110.0  111.0    NaN
train     112.0  113.0  114.0    NaN
bicycle   100.0  101.0  102.0  103.0
airplane    NaN    NaN    NaN    NaN

In [14]:
dfx.dropna(thresh=5, axis=1)

          city1  city2  city3
car       100.0  101.0  102.0
bike      103.0  104.0  105.0
truck     106.0  107.0  108.0
bus       109.0  110.0  111.0
train     112.0  113.0  114.0
bicycle   100.0  101.0  102.0
airplane    NaN    NaN    NaN

In [15]:
ar1 = np.array([100, 200, np.nan, 300])
ser1 = pd.Series(ar1)
ar1.mean(), ser1.mean()

(np.float64(nan), np.float64(200.0))

In [16]:
ser2 = dfx.city4
ser2.sum()

np.float64(253.0)

In [17]:
ser2.mean()

np.float64(126.5)

In [18]:
ser2.cumsum()

car         150.0
bike          NaN
truck         NaN
bus           NaN
train         NaN
bicycle     253.0
airplane      NaN
Name: city4, dtype: float64

In [19]:
filledDf = dfx.fillna(0)
filledDf

          city1  city2  city3  city4  city5
car       100.0  101.0  102.0  150.0    0.0
bike      103.0  104.0  105.0    0.0    0.0
truck     106.0  107.0  108.0    0.0    0.0
bus       109.0  110.0  111.0    0.0    0.0
train     112.0  113.0  114.0    0.0    0.0
bicycle   100.0  101.0  102.0  103.0    0.0
airplane    0.0    0.0    0.0    0.0    0.0

In [20]:
dfx.mean()

city1    105.0
city2    106.0
city3    107.0
city4    126.5
city5      NaN
dtype: float64

In [21]:
filledDf.mean()

city1    90.000000
city2    90.857143
city3    91.714286
city4    36.142857
city5     0.000000
dtype: float64

In [22]:
dfx.city4.fillna(method='ffill')

/tmp/ipykernel_2862/4253246574.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.city4.fillna(method='ffill')

car         150.0
bike        150.0
truck       150.0
bus         150.0
train       150.0
bicycle     103.0
airplane    103.0
Name: city4, dtype: float64

In [23]:
dfx.city4.fillna(method='bfill')

/tmp/ipykernel_2862/483332189.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.city4.fillna(method='bfill')

car         150.0
bike        103.0
truck       103.0
bus         103.0
train       103.0
bicycle     103.0
airplane      NaN
Name: city4, dtype: float64

In [25]:
import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer

df = pd.DataFrame(
    {
        "Size": [1200, np.nan, 1500, 2400, 1100],
        "Price": [300000, 350000, np.nan, 550000, 280000],
        "Location": ["Urban", "Suburban", "Urban", np.nan, "Suburban"],
    }
)

mean_imputer = SimpleImputer(strategy="mean")
df["Size_Mean"] = mean_imputer.fit_transform(df[["Size"]]).ravel()

median_imputer = SimpleImputer(strategy="median")
df["Price_Median"] = median_imputer.fit_transform(df[["Price"]]).ravel()

mode_imputer = SimpleImputer(strategy="most_frequent")
df["Location_Mode"] = mode_imputer.fit_transform(df[["Location"]]).ravel()

num_cols = ["Size", "Price"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = df[num_cols].copy()
df_mice.iloc[:, :] = mice_imputer.fit_transform(df_mice)
df["Size_MICE"] = df_mice["Size"]
df["Price_MICE"] = df_mice["Price"]

print(df)

     Size     Price  Location  Size_Mean  Price_Median Location_Mode  \
0  1200.0  300000.0     Urban     1200.0      300000.0         Urban
1     NaN  350000.0  Suburban     1550.0      350000.0      Suburban
2  1500.0       NaN     Urban     1500.0      325000.0         Urban
3  2400.0  550000.0       NaN     2400.0      550000.0      Suburban
4  1100.0  280000.0  Suburban     1100.0      280000.0      Suburban

     Size_MICE    Price_MICE
0  1200.000000  300000.00000
1  1437.876029  350000.00000
2  1500.000000  362832.14831
3  2400.000000  550000.00000
4  1100.000000  280000.00000